### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by bamorgan13** [kewlfeet/Kickstarter-Clone#1]
### MVP Details
- [ ] Add details to each MVP to indicate what would make that feature complete. For example, Projects may include your simple CRUD functionality ("Users can create project description pages," "Users can view other project pages," "Users can edit their own projects," "Users can delete their own projects," etc.) whereas something like Search would be different (may include things like "Users can search for projects by keyword tags, project names, and descriptions," "Searching for keywords returns an index of matching projects," etc.). These details will help you figure out what exactly you need to implement for each feature as your project moves along.
- [ ] Take a look at the bluebird example wiki [https://github.com/appacademy/bluebird/wiki/mvp-list]() as a reference.

**Comment by kewlfeet** [comment]
Fixed
