### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by bamorgan13** [kewlfeet/Kickstarter-Clone#2]
### format
- [ ] Format your file in markdown so that it displays legibly on github. Follow the Markdown Cheatsheet reference [https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet]() or the zip of the bluebird wiki that is pinned in slack.
### projects
- [ ] I am assuming followers is representing users that have followed and are tracking this project, but not pledged any money. Since a user can follow many projects and a project can have many followers, this would need to be tracked in a `follows` joins table.
- [ ] Tracking a single value for the total amount of funding received can be dangerous. A better approach will be to track each pledge/backing that is made and sum them all up if you ever need a total. (See pledges/backings below)
### follows
- [ ] Add a `follows` table to connect users to projects. It should track its id, user_id, and project_id.
### pledges/backings/etc.
- [ ] When a user backs a project, you'll want to keep track of this association from a couple of different perspectives. You'll want to be able to see what users have backed a particular project, what projects a particular user has backed, and how much money has been pledged to any particular project. Making a `backings` table will allow you to connect all of this information. This will be a joins table between users and projects with the added information of how much money that association represents. You will want to have fields for an id, supporter_id, project_id, and amount.
### rewards
- [ ] Each project has rewards associated with it and minimum pledge amounts to receive that reward. These should be tracked in their own table.
- [ ] A reward should have an id, a title, description, minimum pledge, maximum available, and project_id in order to connect it to the appropriate project. When trying to display a project's rewards you will then be able to use the one-to-many association you set up to get your `@project.rewards` or `@project.reward_ids`, etc.
### userRewards
- [ ] In order to track how many of each reward type have been claimed and what rewards a user has chosen, you will need a joins table to connect these two. You can simply track an id, user_id, and reward_id.

**Comment by kewlfeet** [comment]
fixed
